sudo: false
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
  - rvm: 2.1.8
    env: "RAILS_VERSION=4"
  - rvm: 2.2.4
  - rvm: 2.3.0
  - rvm: ruby-head
bundler_args: "--jobs=3 --retry=3 --without development:production"
cache: bundler
